package value

const (
	ENV_DEVELOPMENT = "development"
	ENV_STAGING     = "staging"
	ENV_PRODUCTION  = "production"
	ENV_TESTING     = "testing"
)
const (
	ENV = "ENV"

	DB_HOST = "DB_HOST"
	DB_PORT = "DB_PORT"
	DB_NAME = "DB_NAME"
	DB_USER = "DB_USER"
	DB_PASS = "DB_PASS"

	DB_MIGRATE_USER = "DB_MIGRATE_USER"
	DB_MIGRATE_PASS = "DB_MIGRATE_PASS"

	MAX_OPEN_CONNS = "MAX_OPEN_CONNS"
	MAX_IDLE_CONNS = "MAX_IDLE_CONNS"

	TEST_DB_HOST = "TEST_DB_HOST"
	TEST_DB_PORT = "TEST_DB_PORT"
	TEST_DB_NAME = "TEST_DB_NAME"
	TEST_DB_USER = "TEST_DB_USER"
	TEST_DB_PASS = "TEST_DB_PASS"

	TEST_DB_MIGRATE_USER = "TEST_DB_MIGRATE_USER"
	TEST_DB_MIGRATE_PASS = "TEST_DB_MIGRATE_PASS"

	REDIS_HOST = "REDIS_HOST"
	REDIS_PASS = "REDIS_PASS"

	TEST_REDIS_HOST = "TEST_REDIS_HOST"
	TEST_REDIS_PASS = "TEST_REDIS_PASS"
)
